name: Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Copia os arquivos do repositório
        uses: actions/checkout@v5

      - name: Instalar o python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      - name: Instalar o poetry
        run: pipx install poetry

      - name: Instalar as dependências
        run: poetry install

      - name: Enter poetry shell
        run: poetry shell

      - name: Rodar os testes
        run: task test

